production_url: http://mattdekenah.github.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://party.dekenah.com" # the base hostname & protocol for your site

# Site settings
title: Five Dekenahs and a Jennings
email: 
description: "Details for 'Five Dekenahs and Jennings' party on 7 April 2017."

# Color settings (hex-codes without the leading hash-tag)

# lime-sage theme
color:
  primary: dbe396
  secondary: d5e35b  
  secondary-dark: 333
  background-dark: 33332f
  background-medium: f2f2ed
  background-light: 

# Build settings
markdown: kramdown
permalink: pretty