production_url: http://nglenday.github.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nicola-and-carl.com" # the base hostname & protocol for your site

# Site settings
title: Nicola and Carl
email: 
description: "Details for Nicola Glenday and Carl Scheffler's wedding on the 19th March 2016"

# Color settings (hex-codes without the leading hash-tag)

# lime-sage theme
color:
  primary: dbe396
  secondary: d5e35b  
  secondary-dark: 333
  background-dark: 33332f
  background-medium: f2f2ed
  background-light: 

# Build settings
markdown: kramdown
permalink: pretty