production_url: http://mattdekenah.github.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mattdekenah.com" # the base hostname & protocol for your site

# Site settings
title: Matthew Dekenah - A South African in Scotland
email: 
description: "South African born software test engineer, politicist, linguist and activist with interests in technology, languages, politics and running."

# Color settings (hex-codes without the leading hash-tag)

# lime-sage theme
color:
  primary: dbe396
  secondary: d5e35b  
  secondary-dark: 333
  background-dark: 33332f
  background-medium: f2f2ed
  background-light: 

# Build settings
markdown: kramdown
permalink: pretty